version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    network_mode: "host"
    depends_on:
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=chat_project.settings
    volumes:
      - .:/app
  redis:
    image: redis:alpine