version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8001
    ports:
      - "8001:8001"
    depends_on:
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=chat_project.settings
    volumes:
      - .:/app

  redis:
    image: redis:alpine