# Generated by Django 5.1 on 2024-09-20 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alter_chatmessage_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('turn', models.IntegerField(default=1)),
                ('koX', models.IntegerField(default=-1)),
                ('koY', models.IntegerField(default=-1)),
                ('koTurn', models.IntegerField(default=-1)),
                ('black_capture_count', models.IntegerField(default=0)),
                ('white_capture_count', models.IntegerField(default=0)),
                ('board', models.JSONField(default=list)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.chatroom')),
            ],
        ),
    ]
