# Generated by Django 5.1 on 2024-10-06 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile',
            field=models.CharField(default='よろしくお願いします', max_length=512),
        ),
    ]
